/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_LEDCONTROL_PROTO_PROTO_TYPES_PB_H_INCLUDED
#define PB_LEDCONTROL_PROTO_PROTO_TYPES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _LEDControl_Proto_ColorType { 
    LEDControl_Proto_ColorType_HSV = 0, 
    LEDControl_Proto_ColorType_RGB = 1 
} LEDControl_Proto_ColorType;

typedef enum _LEDControl_Proto_Data_Type { 
    LEDControl_Proto_Data_Type_ERROR = 0, 
    LEDControl_Proto_Data_Type_TIME = 1, 
    LEDControl_Proto_Data_Type_SET_TIME = 2, 
    LEDControl_Proto_Data_Type_SETUP_STRIP = 3, 
    LEDControl_Proto_Data_Type_PATTERN = 4, 
    LEDControl_Proto_Data_Type_SEQUENCE = 6 
} LEDControl_Proto_Data_Type;

typedef enum _LEDControl_Proto_StripSetup_ColorOrder { 
    LEDControl_Proto_StripSetup_ColorOrder_RGB = 0, 
    LEDControl_Proto_StripSetup_ColorOrder_RBG = 1, 
    LEDControl_Proto_StripSetup_ColorOrder_GRB = 2, 
    LEDControl_Proto_StripSetup_ColorOrder_GBR = 3, 
    LEDControl_Proto_StripSetup_ColorOrder_BRG = 4, 
    LEDControl_Proto_StripSetup_ColorOrder_BGR = 5 
} LEDControl_Proto_StripSetup_ColorOrder;

typedef enum _LEDControl_Proto_Pattern_PatternType { 
    LEDControl_Proto_Pattern_PatternType_ColorValues = 0, 
    LEDControl_Proto_Pattern_PatternType_Gradient = 1, 
    LEDControl_Proto_Pattern_PatternType_Random = 2 
} LEDControl_Proto_Pattern_PatternType;

typedef enum _LEDControl_Proto_Pattern_AnimationType { 
    LEDControl_Proto_Pattern_AnimationType_None = 0, 
    LEDControl_Proto_Pattern_AnimationType_ScrollForward = 1, 
    LEDControl_Proto_Pattern_AnimationType_ScrollBack = 2, 
    LEDControl_Proto_Pattern_AnimationType_TransitionOnce = 3, 
    LEDControl_Proto_Pattern_AnimationType_TransitionPingPong = 4, 
    LEDControl_Proto_Pattern_AnimationType_TransitionRepeat = 5 
} LEDControl_Proto_Pattern_AnimationType;

/* Struct definitions */
typedef struct _LEDControl_Proto_Sequence { 
    pb_callback_t elements; 
} LEDControl_Proto_Sequence;

typedef struct _LEDControl_Proto_Brightness { 
    float value; 
} LEDControl_Proto_Brightness;

typedef struct _LEDControl_Proto_ColorValue { 
    float value1; 
    float value2; 
    float value3; 
} LEDControl_Proto_ColorValue;

typedef struct _LEDControl_Proto_Data { 
    LEDControl_Proto_Data_Type type; 
    pb_callback_t payload; 
} LEDControl_Proto_Data;

typedef struct _LEDControl_Proto_LEDData { 
    LEDControl_Proto_ColorType colorType; 
    pb_callback_t colors; 
} LEDControl_Proto_LEDData;

typedef struct _LEDControl_Proto_Pattern { 
    LEDControl_Proto_ColorType colorType; 
    LEDControl_Proto_Pattern_PatternType patternType; 
    pb_callback_t elements; 
    uint32_t animationRateInMS; 
} LEDControl_Proto_Pattern;

typedef struct _LEDControl_Proto_StripSetup { 
    uint32_t numLEDs; 
    bool rgbw; 
    LEDControl_Proto_StripSetup_ColorOrder colorOrder; 
    uint32_t fps; 
} LEDControl_Proto_StripSetup;

typedef struct _LEDControl_Proto_TimeStamp { 
    uint64_t seconds; 
    uint32_t nanos; 
} LEDControl_Proto_TimeStamp;

typedef struct _LEDControl_Proto_ColorValueWithType { 
    LEDControl_Proto_ColorType type; 
    bool has_colorValue;
    LEDControl_Proto_ColorValue colorValue; 
} LEDControl_Proto_ColorValueWithType;

typedef struct _LEDControl_Proto_Pattern_PatternElement { 
    uint32_t position; 
    bool has_color;
    LEDControl_Proto_ColorValue color; 
} LEDControl_Proto_Pattern_PatternElement;

typedef struct _LEDControl_Proto_SequenceElement { 
    uint32_t durationInMs; 
    bool has_pattern;
    LEDControl_Proto_Pattern pattern; 
} LEDControl_Proto_SequenceElement;


/* Helper constants for enums */
#define _LEDControl_Proto_ColorType_MIN LEDControl_Proto_ColorType_HSV
#define _LEDControl_Proto_ColorType_MAX LEDControl_Proto_ColorType_RGB
#define _LEDControl_Proto_ColorType_ARRAYSIZE ((LEDControl_Proto_ColorType)(LEDControl_Proto_ColorType_RGB+1))

#define _LEDControl_Proto_Data_Type_MIN LEDControl_Proto_Data_Type_ERROR
#define _LEDControl_Proto_Data_Type_MAX LEDControl_Proto_Data_Type_SEQUENCE
#define _LEDControl_Proto_Data_Type_ARRAYSIZE ((LEDControl_Proto_Data_Type)(LEDControl_Proto_Data_Type_SEQUENCE+1))

#define _LEDControl_Proto_StripSetup_ColorOrder_MIN LEDControl_Proto_StripSetup_ColorOrder_RGB
#define _LEDControl_Proto_StripSetup_ColorOrder_MAX LEDControl_Proto_StripSetup_ColorOrder_BGR
#define _LEDControl_Proto_StripSetup_ColorOrder_ARRAYSIZE ((LEDControl_Proto_StripSetup_ColorOrder)(LEDControl_Proto_StripSetup_ColorOrder_BGR+1))

#define _LEDControl_Proto_Pattern_PatternType_MIN LEDControl_Proto_Pattern_PatternType_ColorValues
#define _LEDControl_Proto_Pattern_PatternType_MAX LEDControl_Proto_Pattern_PatternType_Random
#define _LEDControl_Proto_Pattern_PatternType_ARRAYSIZE ((LEDControl_Proto_Pattern_PatternType)(LEDControl_Proto_Pattern_PatternType_Random+1))

#define _LEDControl_Proto_Pattern_AnimationType_MIN LEDControl_Proto_Pattern_AnimationType_None
#define _LEDControl_Proto_Pattern_AnimationType_MAX LEDControl_Proto_Pattern_AnimationType_TransitionRepeat
#define _LEDControl_Proto_Pattern_AnimationType_ARRAYSIZE ((LEDControl_Proto_Pattern_AnimationType)(LEDControl_Proto_Pattern_AnimationType_TransitionRepeat+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LEDControl_Proto_Brightness_init_default {0}
#define LEDControl_Proto_ColorValue_init_default {0, 0, 0}
#define LEDControl_Proto_ColorValueWithType_init_default {_LEDControl_Proto_ColorType_MIN, false, LEDControl_Proto_ColorValue_init_default}
#define LEDControl_Proto_Data_init_default       {_LEDControl_Proto_Data_Type_MIN, {{NULL}, NULL}}
#define LEDControl_Proto_TimeStamp_init_default  {0, 0}
#define LEDControl_Proto_StripSetup_init_default {0, 0, _LEDControl_Proto_StripSetup_ColorOrder_MIN, 0}
#define LEDControl_Proto_LEDData_init_default    {_LEDControl_Proto_ColorType_MIN, {{NULL}, NULL}}
#define LEDControl_Proto_Pattern_init_default    {_LEDControl_Proto_ColorType_MIN, _LEDControl_Proto_Pattern_PatternType_MIN, {{NULL}, NULL}, 0}
#define LEDControl_Proto_Pattern_PatternElement_init_default {0, false, LEDControl_Proto_ColorValue_init_default}
#define LEDControl_Proto_SequenceElement_init_default {0, false, LEDControl_Proto_Pattern_init_default}
#define LEDControl_Proto_Sequence_init_default   {{{NULL}, NULL}}
#define LEDControl_Proto_Brightness_init_zero    {0}
#define LEDControl_Proto_ColorValue_init_zero    {0, 0, 0}
#define LEDControl_Proto_ColorValueWithType_init_zero {_LEDControl_Proto_ColorType_MIN, false, LEDControl_Proto_ColorValue_init_zero}
#define LEDControl_Proto_Data_init_zero          {_LEDControl_Proto_Data_Type_MIN, {{NULL}, NULL}}
#define LEDControl_Proto_TimeStamp_init_zero     {0, 0}
#define LEDControl_Proto_StripSetup_init_zero    {0, 0, _LEDControl_Proto_StripSetup_ColorOrder_MIN, 0}
#define LEDControl_Proto_LEDData_init_zero       {_LEDControl_Proto_ColorType_MIN, {{NULL}, NULL}}
#define LEDControl_Proto_Pattern_init_zero       {_LEDControl_Proto_ColorType_MIN, _LEDControl_Proto_Pattern_PatternType_MIN, {{NULL}, NULL}, 0}
#define LEDControl_Proto_Pattern_PatternElement_init_zero {0, false, LEDControl_Proto_ColorValue_init_zero}
#define LEDControl_Proto_SequenceElement_init_zero {0, false, LEDControl_Proto_Pattern_init_zero}
#define LEDControl_Proto_Sequence_init_zero      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define LEDControl_Proto_Sequence_elements_tag   1
#define LEDControl_Proto_Brightness_value_tag    1
#define LEDControl_Proto_ColorValue_value1_tag   1
#define LEDControl_Proto_ColorValue_value2_tag   2
#define LEDControl_Proto_ColorValue_value3_tag   3
#define LEDControl_Proto_Data_type_tag           1
#define LEDControl_Proto_Data_payload_tag        2
#define LEDControl_Proto_LEDData_colorType_tag   1
#define LEDControl_Proto_LEDData_colors_tag      2
#define LEDControl_Proto_Pattern_colorType_tag   1
#define LEDControl_Proto_Pattern_patternType_tag 2
#define LEDControl_Proto_Pattern_elements_tag    4
#define LEDControl_Proto_Pattern_animationRateInMS_tag 5
#define LEDControl_Proto_StripSetup_numLEDs_tag  1
#define LEDControl_Proto_StripSetup_rgbw_tag     2
#define LEDControl_Proto_StripSetup_colorOrder_tag 3
#define LEDControl_Proto_StripSetup_fps_tag      4
#define LEDControl_Proto_TimeStamp_seconds_tag   1
#define LEDControl_Proto_TimeStamp_nanos_tag     2
#define LEDControl_Proto_ColorValueWithType_type_tag 1
#define LEDControl_Proto_ColorValueWithType_colorValue_tag 2
#define LEDControl_Proto_Pattern_PatternElement_position_tag 1
#define LEDControl_Proto_Pattern_PatternElement_color_tag 2
#define LEDControl_Proto_SequenceElement_durationInMs_tag 1
#define LEDControl_Proto_SequenceElement_pattern_tag 2

/* Struct field encoding specification for nanopb */
#define LEDControl_Proto_Brightness_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             1)
#define LEDControl_Proto_Brightness_CALLBACK NULL
#define LEDControl_Proto_Brightness_DEFAULT NULL

#define LEDControl_Proto_ColorValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    value1,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    value2,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    value3,            3)
#define LEDControl_Proto_ColorValue_CALLBACK NULL
#define LEDControl_Proto_ColorValue_DEFAULT NULL

#define LEDControl_Proto_ColorValueWithType_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  colorValue,        2)
#define LEDControl_Proto_ColorValueWithType_CALLBACK NULL
#define LEDControl_Proto_ColorValueWithType_DEFAULT NULL
#define LEDControl_Proto_ColorValueWithType_colorValue_MSGTYPE LEDControl_Proto_ColorValue

#define LEDControl_Proto_Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           2)
#define LEDControl_Proto_Data_CALLBACK pb_default_field_callback
#define LEDControl_Proto_Data_DEFAULT NULL

#define LEDControl_Proto_TimeStamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seconds,           1) \
X(a, STATIC,   SINGULAR, UINT32,   nanos,             2)
#define LEDControl_Proto_TimeStamp_CALLBACK NULL
#define LEDControl_Proto_TimeStamp_DEFAULT NULL

#define LEDControl_Proto_StripSetup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   numLEDs,           1) \
X(a, STATIC,   SINGULAR, BOOL,     rgbw,              2) \
X(a, STATIC,   SINGULAR, UENUM,    colorOrder,        3) \
X(a, STATIC,   SINGULAR, UINT32,   fps,               4)
#define LEDControl_Proto_StripSetup_CALLBACK NULL
#define LEDControl_Proto_StripSetup_DEFAULT NULL

#define LEDControl_Proto_LEDData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    colorType,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  colors,            2)
#define LEDControl_Proto_LEDData_CALLBACK pb_default_field_callback
#define LEDControl_Proto_LEDData_DEFAULT NULL
#define LEDControl_Proto_LEDData_colors_MSGTYPE LEDControl_Proto_ColorValue

#define LEDControl_Proto_Pattern_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    colorType,         1) \
X(a, STATIC,   SINGULAR, UENUM,    patternType,       2) \
X(a, CALLBACK, REPEATED, MESSAGE,  elements,          4) \
X(a, STATIC,   SINGULAR, UINT32,   animationRateInMS,   5)
#define LEDControl_Proto_Pattern_CALLBACK pb_default_field_callback
#define LEDControl_Proto_Pattern_DEFAULT NULL
#define LEDControl_Proto_Pattern_elements_MSGTYPE LEDControl_Proto_Pattern_PatternElement

#define LEDControl_Proto_Pattern_PatternElement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   position,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             2)
#define LEDControl_Proto_Pattern_PatternElement_CALLBACK NULL
#define LEDControl_Proto_Pattern_PatternElement_DEFAULT NULL
#define LEDControl_Proto_Pattern_PatternElement_color_MSGTYPE LEDControl_Proto_ColorValue

#define LEDControl_Proto_SequenceElement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   durationInMs,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pattern,           2)
#define LEDControl_Proto_SequenceElement_CALLBACK NULL
#define LEDControl_Proto_SequenceElement_DEFAULT NULL
#define LEDControl_Proto_SequenceElement_pattern_MSGTYPE LEDControl_Proto_Pattern

#define LEDControl_Proto_Sequence_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  elements,          1)
#define LEDControl_Proto_Sequence_CALLBACK pb_default_field_callback
#define LEDControl_Proto_Sequence_DEFAULT NULL
#define LEDControl_Proto_Sequence_elements_MSGTYPE LEDControl_Proto_SequenceElement

extern const pb_msgdesc_t LEDControl_Proto_Brightness_msg;
extern const pb_msgdesc_t LEDControl_Proto_ColorValue_msg;
extern const pb_msgdesc_t LEDControl_Proto_ColorValueWithType_msg;
extern const pb_msgdesc_t LEDControl_Proto_Data_msg;
extern const pb_msgdesc_t LEDControl_Proto_TimeStamp_msg;
extern const pb_msgdesc_t LEDControl_Proto_StripSetup_msg;
extern const pb_msgdesc_t LEDControl_Proto_LEDData_msg;
extern const pb_msgdesc_t LEDControl_Proto_Pattern_msg;
extern const pb_msgdesc_t LEDControl_Proto_Pattern_PatternElement_msg;
extern const pb_msgdesc_t LEDControl_Proto_SequenceElement_msg;
extern const pb_msgdesc_t LEDControl_Proto_Sequence_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LEDControl_Proto_Brightness_fields &LEDControl_Proto_Brightness_msg
#define LEDControl_Proto_ColorValue_fields &LEDControl_Proto_ColorValue_msg
#define LEDControl_Proto_ColorValueWithType_fields &LEDControl_Proto_ColorValueWithType_msg
#define LEDControl_Proto_Data_fields &LEDControl_Proto_Data_msg
#define LEDControl_Proto_TimeStamp_fields &LEDControl_Proto_TimeStamp_msg
#define LEDControl_Proto_StripSetup_fields &LEDControl_Proto_StripSetup_msg
#define LEDControl_Proto_LEDData_fields &LEDControl_Proto_LEDData_msg
#define LEDControl_Proto_Pattern_fields &LEDControl_Proto_Pattern_msg
#define LEDControl_Proto_Pattern_PatternElement_fields &LEDControl_Proto_Pattern_PatternElement_msg
#define LEDControl_Proto_SequenceElement_fields &LEDControl_Proto_SequenceElement_msg
#define LEDControl_Proto_Sequence_fields &LEDControl_Proto_Sequence_msg

/* Maximum encoded size of messages (where known) */
/* LEDControl_Proto_Data_size depends on runtime parameters */
/* LEDControl_Proto_LEDData_size depends on runtime parameters */
/* LEDControl_Proto_Pattern_size depends on runtime parameters */
/* LEDControl_Proto_SequenceElement_size depends on runtime parameters */
/* LEDControl_Proto_Sequence_size depends on runtime parameters */
#define LEDControl_Proto_Brightness_size         5
#define LEDControl_Proto_ColorValueWithType_size 19
#define LEDControl_Proto_ColorValue_size         15
#define LEDControl_Proto_Pattern_PatternElement_size 23
#define LEDControl_Proto_StripSetup_size         16
#define LEDControl_Proto_TimeStamp_size          17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
