/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LEDControl_Proto_Brightness, LEDControl_Proto_Brightness, AUTO)


PB_BIND(LEDControl_Proto_ColorValue, LEDControl_Proto_ColorValue, AUTO)


PB_BIND(LEDControl_Proto_ColorValueWithType, LEDControl_Proto_ColorValueWithType, AUTO)


PB_BIND(LEDControl_Proto_Data, LEDControl_Proto_Data, AUTO)


PB_BIND(LEDControl_Proto_Error, LEDControl_Proto_Error, AUTO)


PB_BIND(LEDControl_Proto_Status, LEDControl_Proto_Status, AUTO)


PB_BIND(LEDControl_Proto_TimeStamp, LEDControl_Proto_TimeStamp, AUTO)


PB_BIND(LEDControl_Proto_StripSetup, LEDControl_Proto_StripSetup, AUTO)


PB_BIND(LEDControl_Proto_LEDData, LEDControl_Proto_LEDData, AUTO)


PB_BIND(LEDControl_Proto_Pattern, LEDControl_Proto_Pattern, AUTO)


PB_BIND(LEDControl_Proto_Pattern_PatternElement, LEDControl_Proto_Pattern_PatternElement, AUTO)


PB_BIND(LEDControl_Proto_SequenceElement, LEDControl_Proto_SequenceElement, AUTO)


PB_BIND(LEDControl_Proto_Sequence, LEDControl_Proto_Sequence, AUTO)








